### ISSUE TITLE
Implement jump-to-line feature

### ISSUE THREAD

**Issue by miqlas** [KapiX/Koder#1]
Like in Pe in left-bottom corner. It would be great to specify the line at opening too, to let things open for example from TextSearch or grep with defined line.

**Comment by KapiX** [comment]
There is jump-to-line feature - Ctrl+G. However, it is not accessible from command line yet. Do you have any preferred syntax for that?
For Pe-like status bar you should create another issue.

**Comment by miqlas** [comment]
I think it is "filename:lineno" but i have to check it.
Or "filename:lineno:column" like the gcc error messages.

Maybe you know already, but any Text like this becomes a clickable link in Haiku Terminal if you press the Alt key. It pass the clicked "link" as args to the /bin/open command. Cool Feature!

**Comment by KapiX** [comment]
Remaining part of this implemented in 078fd87118723a46881c46a8863a00c81bb3cdaa.
TextSearch still won't work though: https://dev.haiku-os.org/ticket/13289.
