### ISSUE TITLE
Implement a directory tree view

### ISSUE THREAD

**Issue by extrowerk** [KapiX/Koder#10]
NerdTree does a great job for easy file navigation in a Project folder. Something like that would be nice to have.

**Comment by KapiX** [comment]
I am thinking about implementing this using Trackers scripting support (+ stack and tile APIs). Would that be enough?

**Comment by extrowerk** [comment]
I thhink that could be enough. Thanks KapiX!

Kacper Kasper <notifications@github.com>:

**Comment by KapiX** [comment]
This is more of an IDE feature and should already be somewhat remedied with navigation button in lower left corner. Closing.
