### ISSUE TITLE
Scrolling is not work well by change of BScrollView

### ISSUE THREAD

**Issue by hanya** [KapiX/Koder#105]
The vertical scrollbar is not updated well and scrolling by mouse wheel is too large. 
It looks the problem is caused by the change of default flag of BScrollView.
https://git.haiku-os.org/haiku/commit/?id=5b0e5c0ac69c48a80144df8611fc024a5ef184a1

**Comment by KapiX** [comment]
Fixed in https://sourceforge.net/p/scintilla/haiku/ci/10f977e61c598067f68cc90964232a21206a761f/.
