### ISSUE TITLE
Minor GUI issues

### ISSUE THREAD

**Issue by humdingerb** [KapiX/Koder#106]
* The Bookmarks window title isn't translatable.
* In the preferences, the "Margins" label isn't quite right. "Margins" suggests space all around the 'work area', while it's actually only the column to its left. Similar to the 'Toolbar', I suggest 'Infobar'. While not perfect - the folding widgets go beyond information - it's a bit better IMO.
* In the preferences, under "Behavior", the "NL" of the first checkbox label is a bit cryptic. How about: "Add empty line at the end if not present (on save)"?

**Comment by KapiX** [comment]
2. How about "Left margin features"?
3. I know; I didn't want the label to be too long, because the window gets unnecessarily large. I'll be reworking the prefs window for the next version because it is getting really crowded, but it will stay that way (along with the label in question) for 0.5.

**Comment by humdingerb** [comment]
-> 2. or just "Left margin"
-> 3. or "Ensure empty last line on save"
