### ISSUE TITLE
Add an application icon

### ISSUE THREAD

**Issue by miqlas** [KapiX/Koder#11]
Koder haven't got any icon yet. It NEEDS a nice icon.

**Comment by KapiX** [comment]
Unfortunately, I don't have necessary skills.
Contributions welcome.

**Comment by miqlas** [comment]
Maybe this one? https://github.com/KapiX/Koder/pull/16

**Comment by KapiX** [comment]
Fixed with 21e3eba719da89183ebf7482e7bf31181f7c5834.
