### ISSUE TITLE
Incorrectly detects RO FSes *and* does not error on save

### ISSUE THREAD

**Issue by waddlesplash** [KapiX/Koder#114]
1. Mount a drive as read-only.
2. Open some file in Koder.
3. Modify and try to save it.

No error is presented and it appears to have saved successfully, which of courses it did not.

**Comment by waddlesplash** [comment]
What about the case where saving fails for some other reason? Shouldn't that actually warn the user?

**Comment by KapiX** [comment]
There is a TODO about this since the beginning of the project (I think):
https://github.com/KapiX/Koder/blob/4cf43c9da51ed76983929a693022558fa3fc081b/src/windows/EditorWindow.cpp#L378

I didn't address it now because it would involve adding new strings, and I want to pull the fix into 0.5.1.
