### ISSUE TITLE
Crash when opening "Edit"->"Koder Preferences" on the menu bar

### ISSUE THREAD

**Issue by R4H33M** [KapiX/Koder#127]
To replicate -> open koder, open "Edit" on the menu bar and click on "Koder preferences" on the bottom.

**Comment by humdingerb** [comment]
Crashes with the latest compiled Koder sources as well:
this is the debug report: https://linx.li/koder-72939-debug-13-12-2019-18-35-15.report

Does NOT crash when built with DEBUGGER := TRUE
