### ISSUE TITLE
Dropping a color strange behaviour

### ISSUE THREAD

**Issue by extrowerk** [KapiX/Koder#135]
Undo reveals that dropping a color (from Colors!) onto a line the color hexa-code got inserted and gets instantly overwritten with the current content of the clipboard.

How to reproduce:
- Open a textfile in Koder
- Open Colors!
- Cöüy some text
- Drop a color onto an empty line.

Maybe it is a bug in Haiku, idk.

**Comment by extrowerk** [comment]
Cöüy some text = Copy some text, cant edit in WP.

**Comment by KapiX** [comment]
This is a problem with Colors!.

It uses "Simple Drag'n'Drop" "protocol" which is [described in BeBook](https://www.haiku-os.org/legacy-docs/bebook/DragAndDrop.html#id543251) as useful for "dragging and dropping which takes place within a single application, or within a tightly coupled set of applications which "know about" one another." This case is neither single application nor a set of applications that would know about each other, so I consider it invalid.

The reason for overwriting with clipboard contents is that Colors! uses [`B_PASTE` as `what`](https://github.com/HaikuArchives/Colors/blob/master/ColorPicker/ColorPreview.cpp#L133). Currently Scintilla takes the dropped message and just [passes it without change to `BView` for handling](http://hg.code.sf.net/p/scintilla/haiku/file/a947e67da935/ScintillaHaiku.cxx#l505), and the default action for `B_PASTE` would be to insert clipboard contents.

While there is work on Scintilla side on actually implementing negotiated drag'n'drop, it would not fix this problem.
Colors! should use something like `B_SIMPLE_DATA` for drag message, this has more chance of being correctly recognized by a wider set of applications going into the future. However, I do recognize that `B_PASTE` itself might have been some kind of compatibility hack.
