### ISSUE TITLE
Clicking on a Url-Link in BePDF will try to open Koder, then crash (Haiku 64bit, nightly) Hrev 55102+1

### ISSUE THREAD

**Issue by Brunobasta** [KapiX/Koder#137]
Opened a .pdf file with BePDF. Clicking on: " https://datatracker.ietf.org/drafts/current/"
http://0x0.st/-eIB.png
Errorlog from BePDF: http://0x0.st/-eIu.png

Bugreport here: http://0x0.st/-eIQ.report

Why BePDF tries to open the link with Koder and not with Web+?
Is it a BePDF mistake?

**Comment by KapiX** [comment]
I'm not sure, but my guess is that this is FileTypes problem. I've seen it in an opposite direction - C++ files being opened as XML/HTML with Web+ because they had a lot of `<>` at the beginning.

Anyway, this is also a legitimate problem in Koder so the issue should stay open.
