### ISSUE TITLE
Vertcal scrollbar glitch

### ISSUE THREAD

**Issue by extrowerk** [KapiX/Koder#138]
A textfile which doesn't fits into the visible text-area should resize the scrollbar proportionally. Koder frequently fails at this.

I have seen some files which doesn't fits vertically, but the scrollbar is still drawn full-height. It looks like the document is notscrollable, but one can still scroll with the mouse scroll-wheel or with the keyboard.

I also experienced cases, where the scrollbar wrongly resized, moving it with the mouse to the bottom doesn't actually scroll to the end of the file, as the bar size is wrong. One can scroll "further" with the mouse wheel or with the keyboard.

I haven't yes experienced similar problem with the horizontal scrollbar.

**Comment by extrowerk** [comment]
Oh, i didn't wanted to close the issue.

**Comment by KapiX** [comment]
Fixed in https://sourceforge.net/p/scintilla/haiku/ci/ece6972b0f9e2c1552141c9329ba2939fb831cbc/.

**Comment by extrowerk** [comment]
It just happend again.
Either the patch is not complete, or the fix did not landed in the HaikuPorts repo yet.
