### ISSUE TITLE
I'd like to post a fix for "Koder 0.5.3", but I can't make a pull request.

### ISSUE THREAD

**Issue by FuRuYa7** [KapiX/Koder#139]
The Create Pull Request button in the lower right corner is missing from the Compare Changes screen, probably because you need to switch "tags" in the middle of the operation.

All I have to do is press the Create Pull Request button, but I don't know what to do. 

I'm sorry, but there are few corrections, so please use it as it is. 

-

#### The link just before the pull request:

[FuRuYa7: Comparing changes](https://github.com/KapiX/Koder/compare/0.5.3...FuRuYa7:develop2?expand=1)

**Comment by FuRuYa7** [comment]
When I added a translation file, the added language was not added to the "Makefile" locale.
Translations may not have been applied in many other languages. 

Makefile:

```
- LOCALES = de en en_GB es fr pt pl ro ru uk
+ LOCALES = ca de en en_GB es fi fr fur hu id it ja lt pl pt ro ru sv tr uk
```

**Comment by FuRuYa7** [comment]
An error occurs when converting a translation file at build time.  Removed the blank line on line 64 of "ja.catkeys". 

locales/ja.catkeys:

```
Unix format	EditorWindow		Unix 形式
Unsaved changes	EditorWindow		保存されていない変更
Untitled	EditorWindow		無題
-
View	EditorWindow		表示
Windows format	EditorWindow		Windows 形式
Wrap lines	EditorWindow		行を折り返す
```

**Comment by FuRuYa7** [comment]
I've made a few pull requests, and I'm sorry, this is the first time I've used an old "master" branch. 

It's a hassle, but make sure you have the latest version in the "master" branches and "tag" . This allows you to make pull requests even if you have low git skills. 

I think I can contribute even if my git skill is low.

**Comment by KapiX** [comment]
It seems I forgot to add new languages to Makefile when synchronizing translations :/

I have created a Pull Request: https://github.com/KapiX/Koder/pull/140 - more comments there.

(You were trying to add more commits to a tag, which itself is a commit, so that's not possible. You should have chosen a branch, 0.5 in this case.)
