### ISSUE TITLE
Suggestion: Allow closing the Find/Replace dialog by pressing ESC

### ISSUE THREAD

**Issue by OscarL** [KapiX/Koder#142]
Pretty much the title says it all. It would help with my muscle memory while switching OSes/editors if Koder allowed for the Find/Replace dialog to be dismissed by hitting the ESC key.

Thanks for your work! Much appreciated!

**Comment by Begasus** [comment]
+1 for me also

**Comment by KapiX** [comment]
This was added long time ago in https://github.com/KapiX/Koder/commit/70ac46d78be538f2488ed4ff02791c5f2dd9f610 (released with 0.5.0). Is it not working? (Works for me.)
