### ISSUE TITLE
Drag&dropping a file opens twice

### ISSUE THREAD

**Issue by humdingerb** [KapiX/Koder#22]
When drag&dropping a file, it's opened twice. Doesn't happen when double-clicking a file.

**Comment by KapiX** [comment]
Invalid. Your Scintilla is too old. This has been fixed in 3.7.3.
https://sourceforge.net/p/scintilla/haiku/ci/2fbcfa0304707e401c69f2aadae2b9ef9525ce96/

**Comment by humdingerb** [comment]
Oh, sorry. You know, the newer scintilla_x86 won't let me compile Koder... :)
