### ISSUE TITLE
Windows don't cascade

### ISSUE THREAD

**Issue by humdingerb** [KapiX/Koder#23]
When opening several files at once, they should cascade. Right now they are opened exactly on top of each other.
Also nice would be to automatically stack them with S&T.

**Comment by KapiX** [comment]
I have added an option to create window stacks, but it won't work when opening multiple files from Tracker, because for some reason Tracker sends a separate message for each file.
It creates a nice stack when you drop multiple files on Koder, though :)
Also, opening files from Tracker won't attach them to currently active window. This is what I would expect, but if you think it should work differently, let me know.

**Comment by humdingerb** [comment]
Nice!
Maybe simplify the option label to "Stack new windows".

FWIW, if you open a group of files by selecting them an using the "Open with >" context menu, they do open stacked. But if you set Koder as preferred app and just "Open" a selection of files, it doesn't, as you said above. Maybe Tracker can be fixed...

Here is what I wanted to comment, but when finished changed my mind about it:
> One thing I would expect: If you have a file open in Koder, drag&dropping more files on its window should stack all those files onto that window. Currently it opens those files stacked onto each other, but not onto the window the files were dropped on.
> If you just open another file while A koder window is already open, I agree, the new window shouldn't be stacked to it. Drag&dropping is different, however.

Actually, I often drop a file onto Pe, that I wouldn't necessarily want to have stacked to it...
It may be neat to do it like SoundPlay: depending where you drop files, SoundPlay would either add the files to the playlist, or replace the current playlist with those files IIRC. It signaled that with a green or blue ant-line at the view border, I think.

As long as there's a tool bar, you could stack-to-this-window when dropped there or not when dropped anywhere else. What if the user disables the tool bar? I dunno... :)

**Comment by KapiX** [comment]
> It may be neat to do it like SoundPlay: depending where you drop files, SoundPlay would either add the files to the playlist, or replace the current playlist with those files IIRC. It signaled that with a green or blue ant-line at the view border, I think.

This is actually a good idea. I am not going to implement it anytime soon, but feel free to open an issue.
