### ISSUE TITLE
Change displayed toolbar icons

### ISSUE THREAD

**Issue by humdingerb** [KapiX/Koder#25]
Suggestion:

* Open file
* Reload (revert to last saved version)
* Save file (with the "disabled" icon when there are no unsaved changes)
* Save as...
* --------- Separator
* Undo
* Redo
* --------- Separator
* Whitespaces on/off
* Softwrap on/off
* --------- Separator
* Preferences
* Find

**Comment by KapiX** [comment]
I am going to leave softwrap out for now. There is no way to force Scintilla to wrap at specific column (only window width), so the icon is a bit misleading. I might try to implement this feature in Scintilla itself (and hopefully upstream it), but I'd like to focus on the editor itself at this moment.
