### ISSUE TITLE
Add status bar

### ISSUE THREAD

**Issue by humdingerb** [KapiX/Koder#30]
The functionality of Pe's and StyledEdit's status bar is something I use quite often. That is, being able to navigate the filesystem to open files and folders. As it's a bit unintuitive to get to the drill-down navigation by clicking on the line number, I suggest using a symbol like http://unicode.scarfboy.com/dhkupefwz.html?s=U%2B2388 . Looks a bit like a nautical wheel...

Also, while Koder as the obvious line numbers, there's no column number for the caret. To be complete, though, I suggest "line, column" like Pe does.

There could be more info and functionality down there, like StyledEdit's indicator for read-only files, which acts as pop-up menu to "Unlock file". Not sure something similar for encoding is needed...

**Comment by waddlesplash** [comment]
For me, the line/column number is more useful than the files; but that's neat too :)

**Comment by KapiX** [comment]
@humdingerb Would you expect this menu with files to always open them with Koder, or should it behave like in StyledEdit (it goes to Tracker and opens with preferred application)? I'd say it's better to always open with Koder, with the exception of directories of course. With Tracker you'd get „Unknown type” dialog and that could quickly get annoying.

**Comment by humdingerb** [comment]
Actually, I'd prefer to open files with Tracker, i.e. their preferred app.
In case of source files, that's most probably Koder (if the user uses Koder as default coding app). This is probably the most common usage. When it's an icon -> I-O-M, wav -> MediaPlayer, pdf -> BePDF. You can even start the latest built of your app from the objects folder...
Sounds most useful to me.

> With Tracker you'd get „Unknown type” dialog and that could quickly get annoying.

I never see those... They come from unrecognized file types? 
I'd use that drill-down-menu to open files relating to the current project or some project in the parent "Sources" folder. They normally don't contain unknown files.

**Comment by KapiX** [comment]
But if you don't use Koder as preferred app, opening files with Pe or something else from that menu can be confusing.
There is also an issue of opening files in stack. If they go through Tracker I can't pass an argument that would tell it to attach the new window to existing stack.

**Comment by humdingerb** [comment]
True.
How about opening all Koder supported file types in Koder and non-supported with Tracker?

**Comment by KapiX** [comment]
Implemented without file unlocking in a94b0bd88fc96ec1d232bf5ab7b7a1dadf659e4f.
