### ISSUE TITLE
Add a tool to launch Koder from the command line

### ISSUE THREAD

**Issue by waddlesplash** [KapiX/Koder#39]
Pe has `lpe`, which allows you to launch Pe from the command line, and will not exit until you've closed the newly-opened Pe window for that file (which means you can use it as Git editor, for instance.) Pe places this binary and *only* this binary in PATH; i.e. the main `Pe` binary is not in PATH.

It seems that launching Koder from the command line is kind of broken anyway (i.e. if you use a relative rather than absolute path, it looks for the file starting in `~` and not `pwd`.)

**Comment by KapiX** [comment]
I don't like Pe's approach with two executables. After several approaches I have finally figured out how to do it in one executable :). Koder now has --wait switch (like VS Code) that makes it wait for the window to close before returning.
It doesn't support piping yet but there's TODO for that. It certainly works with git now.
