### ISSUE TITLE
JavaScript support?

### ISSUE THREAD

**Issue by ryanpcmcquen** [KapiX/Koder#50]
Thanks for making Koder! I love using it, but it would be awesome if it had JavaScript support ... not really sure what is involved in that. Can we use anything from SciTE or Textadept?

**Comment by KapiX** [comment]
I have explained the process for PHP here: https://discuss.haiku-os.org/t/koder-new-native-code-editor/4480/39

I will be adding support for PHP, HTML and JS in a week or so.

**Comment by KapiX** [comment]
Fixed in f4df5eb69a15bc28ee259071aee0a13278c89052.
