### ISSUE TITLE
Koder hangs under recent Haiku builds & segfaults under guarded heap

### ISSUE THREAD

**Issue by waddlesplash** [KapiX/Koder#53]
I am on hrev52355, and just today took the Scintilla upgrade from 4.1.0-3 to 4.1.1-1.

Ever since then, Koder hangs rather regularly (i.e. all windows stop redrawing and CPU use goes to 100%.) Attaching the debugger shows it's somehow looping in malloc() in TLSBlock code. I tried running under MALLOC_DEBUG=g, but it immediately crashed during bitmap creation.

**Comment by KapiX** [comment]
Should be fixed in Scintilla 4.1.2.
