### ISSUE TITLE
Add supported mime-types

### ISSUE THREAD

**Issue by miqlas** [KapiX/Koder#6]
Koder supports some different source file type (like C, Python, etc.) but it doesn't show up in Tracker right click menu as supported editor. I suppose Koder doesn't define the supported mime-types. It should define the same like Pe does.

**Comment by KapiX** [comment]
It does define supported MIME types, and it shows for me in the menu if it is run at least once.
Can you give detailed steps to reproduce?

**Comment by miqlas** [comment]
It works, we can close this ticket.
