### ISSUE TITLE
Better handling of read only files

### ISSUE THREAD

**Issue by diversys** [KapiX/Koder#69]
Due to a read only nature of hpkg packages a lot of files in Haiku are read only. Having to view system headers shows an alert each time one wants to open it. Some other way is needed to avoid it.

**Comment by KapiX** [comment]
This alert is by design. I've been bitten so many times I can't even count by opening read-only files (usually from tars) in Pe, editing them and then not being able to save them. I figured it's better to show it before, than after.

**Comment by diversys** [comment]
Maybe some image/text can be displayed in statusbar/toolbar showing that the file is r/o?

**Comment by Konrad77** [comment]
I like how Apple does this in XCode. Opening them says nothing, but you cant change the files (Framework files). In some cases like Cocoapods, they say something like: "The file is readonly, do you wan't to write changes? [YES] [NO].
