### ISSUE TITLE
Disable blinking of carret on non-active editor

### ISSUE THREAD

**Issue by hanya** [KapiX/Koder#70]
When I open 10 or more files by Koder on virtual environment (single CPU setting), the system performance was really bad.
The reason of the problem seems the blinking of the carret on each editor even they are non-active.
When I add fEditor->SendMessage(SCI_SETCARETPERIOD, -1, 0); to supress blinking carret, the slow down was solved.

**Comment by KapiX** [comment]
Should be fixed by https://sourceforge.net/p/scintilla/haiku/ci/db40816418604078556d05ebbde71fef3464b44c/.
