### ISSUE TITLE
Koder doesnt remember carret position

### ISSUE THREAD

**Issue by Konrad77** [KapiX/Koder#72]
When switching between .h/.cpp with the Opt + O, Koder offsets the Carret position to 0.0 everytime I switch file. Would be nice if it could remember the position (open files) so you dont have to scroll to where you were.

**Comment by Konrad77** [comment]
I just switch between them. I am using 0.4 from HaikuDepot. I'll see if I can reproduce it when I am back at home.

**Comment by Konrad77** [comment]
I switch between them using CMD + O. Launching the file again from tracker will activate the correct Window in Koder. It doesnt not open a new window.

**Comment by Konrad77** [comment]
I have a video of it, want me to upload it (.mov)?

**Comment by Konrad77** [comment]
Here is a video @KapiX https://ufile.io/0q6x4
Its a .mov file created on OSX. I hope you can watch it.

**Comment by KapiX** [comment]
I have reproduced it on 0.4 branch. It doesn't happen on master. Apparently I have fixed it somewhere along the way. ¯\\\_(ツ)\_/¯
