### ISSUE TITLE
Koder preferences: Spaces per tab setting does not persist

### ISSUE THREAD

**Issue by dcatt-haiku** [KapiX/Koder#73]
Changing the _Spaces per tab_ does not persist (after I **Apply** the change).  I tried changing this for the case of Ruby from 4 to 2 and it didn't take affect.

**Comment by KapiX** [comment]
Do you have .editorconfig active?

**Comment by dcatt-haiku** [comment]
_Use .editorconfig if possible_ is enabled (if that's what you're asking).

**Comment by dcatt-haiku** [comment]
Disabled the _Use .editorconfig if possible_ and still can replicate the issue.  I will say that other settings like _Convert tabs into spaces_ (for example) persist.
