### ISSUE TITLE
Click in scrollbar should scroll one page

### ISSUE THREAD

**Issue by humdingerb** [KapiX/Koder#83]
Clicking above or below the knob in the scrollbar usually scrolls the contents up/down one page. In Koder it currently scrolls only a fixed 10 lines.

[BTW, the horizontal scrollbar is only decorative, right? I mean, the text wraps at the window border, so a horizontal scrollbar isn't really needed besides filling the otherwise awkward empty space beside the statusbar. Maybe the knob could be filling the whole space, which would be less distracting.
Or the space could be used for other status/help/ whatever messages, like what's currently in find / replace. Or something...]

**Comment by humdingerb** [comment]
Oops. I missed the setting "Wrap lines"... That would make the hor. scrollbar not decorative, I guess. :)
Still, if the "Wrap lines" is on, the knob could fill the scrollbar.

**Comment by KapiX** [comment]
Fixed in https://sourceforge.net/p/scintilla/haiku/ci/10f977e61c598067f68cc90964232a21206a761f/.
