### ISSUE TITLE
Toolbar icons for bookmark navigation

### ISSUE THREAD

**Issue by humdingerb** [KapiX/Koder#84]
If you want to include tool bar icons for next/previous bookmark jumping, I'd have these that I could send a PR for:

![Bookmark icons](https://0x0.st/sD0S.png)

The Bookmarks icon is the same I did for BePDF. Maybe it can be used should Koder get an extra window for managing bookmarks in the future.

**Comment by KapiX** [comment]
It will as part of #29 so PR would be nice.
