### ISSUE TITLE
File opens with remembered position at bottom of window

### ISSUE THREAD

**Issue by humdingerb** [KapiX/Koder#90]
Currently, when you open a file it's scrolled to the last caret position, highlighting the row. But the highlighted row is at the bottom of the window.
To me, it'd feel more natural to have the contents scrolled so that the highlighted row is at the top, or maybe even better in the middle (or the top quarter) of the window. That way you see also what's above the last remembered position, which helps orientation.

**Comment by diversys** [comment]
I too think the top quarter would be best as you can see surroundings right away.

**Comment by KapiX** [comment]
It's 8 lines from the top, I think that's enough?

**Comment by humdingerb** [comment]
I just updated, very nice!
