### ISSUE TITLE
"Replace and find" doesn't jump to next find

### ISSUE THREAD

**Issue by humdingerb** [KapiX/Koder#94]
"Replace and find" should jump to next find automatically after replacing the string.

**Comment by deejam** [comment]
Is "Replace and find" a replace then find functionallity, or a find then replace functionallity?

If it is find then replace, then it should be named "Find and replace".

**Comment by KapiX** [comment]
I can't reproduce it. Can you provide exact steps?

**Comment by humdingerb** [comment]
Indeed, I cannot with the latest build + scintilla here. Fixed! :)

**Comment by KapiX** [comment]
Cool. You might have created some specific conditions, the code responsible for this has a lot of edge cases and not all of them are well tested ("In selection" for example).
